services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=newConeu'
      - 'MONGO_INITDB_ROOT_PASSWORD=patrelaEstrick'
      - 'MONGO_INITDB_ROOT_USERNAME=patrelaEstrick'
    ports:
      - '27017:27017'
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=newConeu'
      - 'POSTGRES_PASSWORD=patrelaEstrick'
      - 'POSTGRES_USER=patrelaEstrick'
    ports:
      - '5432:5432'

